platform :ios, '9.0'

target 'OpalImagePickerDemo' do
  use_frameworks!

  pod 'OpalImagePicker', path: '..'

  target 'OpalImagePickerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


swift4 = ['OpalImagePicker']

post_install do |installer|
    installer.pods_project.targets.each do |target|
        swift_version = nil
        
        if swift4.include?(target.name)
            swift_version = '4.2'
        end
        
        if swift_version
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = swift_version
            end
        end
    end
end
